import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  DEFAULT_THEME_CSS_PATHS,
  discoverThemeContract,
  mergeThemesFromContract,
} from './parse-theme-css'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')

function emitMapAsObjectLiteral(map: Map<string, string>, indent: string): string {
  const keys = [...map.keys()].sort()
  return keys
    .map((k) => `${indent}${JSON.stringify(k)}: ${JSON.stringify(map.get(k)!)}`)
    .join(',\n')
}

const cssTexts = DEFAULT_THEME_CSS_PATHS.map((rel) =>
  readFileSync(path.join(root, rel), 'utf8'),
)
const contract = discoverThemeContract(cssTexts)
const resolved = mergeThemesFromContract(cssTexts, contract)

const themeBlocks = contract.themes
  .map((t) => {
    const map = resolved[t.id]
    return `  ${JSON.stringify(t.id)}: {\n${emitMapAsObjectLiteral(map, '    ')}\n  }`
  })
  .join(',\n')

const outPath = path.join(root, 'src/tokens/css-theme.generated.ts')
const banner = `/**
 * Auto-generated by scripts/generate-theme-tokens.ts from:
 * - ${DEFAULT_THEME_CSS_PATHS.join('\n * - ')}
 *
 * Theme ids are discovered from CSS (see scripts/parse-theme-css.ts): :root / .dark / .theme-*.
 * Do not edit by hand. Run \`pnpm generate:tokens\` after changing theme CSS.
 */
`

const body = `export const themeCssVars = {
${themeBlocks},
} as const

export type ThemeCssVars = typeof themeCssVars
export type ThemeId = keyof typeof themeCssVars
`

writeFileSync(outPath, `${banner}${body}`, 'utf8')

const counts = contract.themes
  .map((t) => `${t.id}:${resolved[t.id].size}`)
  .join(', ')
console.log(`Wrote ${path.relative(root, outPath)} (${counts})`)
