/**
 * Auto-generated by scripts/generate-theme-tokens.ts from:
 * - src/index.css
 * - src/styles/overrides.css
 *
 * Theme ids are discovered from CSS (see scripts/parse-theme-css.ts): :root / .dark / .theme-*.
 * Do not edit by hand. Run `pnpm generate:tokens` after changing theme CSS.
 */
export const themeCssVars = {
  "light": {
    "--accent": "oklch(0.97 0 0)",
    "--accent-foreground": "oklch(0.205 0 0)",
    "--background": "oklch(1 0 0)",
    "--border": "oklch(0.922 0 0)",
    "--card": "oklch(1 0 0)",
    "--card-foreground": "oklch(0.145 0 0)",
    "--chart-1": "oklch(0.871 0.15 154.449)",
    "--chart-2": "oklch(0.723 0.219 149.579)",
    "--chart-3": "oklch(0.627 0.194 149.214)",
    "--chart-4": "oklch(0.527 0.154 150.069)",
    "--chart-5": "oklch(0.448 0.119 151.328)",
    "--destructive": "oklch(0.577 0.245 27.325)",
    "--foreground": "oklch(0.145 0 0)",
    "--input": "oklch(0.922 0 0)",
    "--muted": "oklch(0.97 0 0)",
    "--muted-foreground": "oklch(0.556 0 0)",
    "--popover": "oklch(1 0 0)",
    "--popover-foreground": "oklch(0.145 0 0)",
    "--primary": "oklch(0.527 0.154 150.069)",
    "--primary-foreground": "oklch(0.982 0.018 155.826)",
    "--radius": "0.625rem",
    "--ring": "oklch(0.708 0 0)",
    "--secondary": "oklch(0.967 0.001 286.375)",
    "--secondary-foreground": "oklch(0.21 0.006 285.885)",
    "--sidebar": "oklch(0.985 0 0)",
    "--sidebar-accent": "oklch(0.97 0 0)",
    "--sidebar-accent-foreground": "oklch(0.205 0 0)",
    "--sidebar-border": "oklch(0.922 0 0)",
    "--sidebar-foreground": "oklch(0.145 0 0)",
    "--sidebar-primary": "oklch(0.627 0.194 149.214)",
    "--sidebar-primary-foreground": "oklch(0.982 0.018 155.826)",
    "--sidebar-ring": "oklch(0.708 0 0)"
  },
  "dark": {
    "--accent": "oklch(0.269 0 0)",
    "--accent-foreground": "oklch(0.985 0 0)",
    "--background": "oklch(0.145 0 0)",
    "--border": "oklch(1 0 0 / 10%)",
    "--card": "oklch(0.205 0 0)",
    "--card-foreground": "oklch(0.985 0 0)",
    "--chart-1": "oklch(0.871 0.15 154.449)",
    "--chart-2": "oklch(0.723 0.219 149.579)",
    "--chart-3": "oklch(0.627 0.194 149.214)",
    "--chart-4": "oklch(0.527 0.154 150.069)",
    "--chart-5": "oklch(0.448 0.119 151.328)",
    "--destructive": "oklch(0.704 0.191 22.216)",
    "--foreground": "oklch(0.985 0 0)",
    "--input": "oklch(1 0 0 / 15%)",
    "--muted": "oklch(0.269 0 0)",
    "--muted-foreground": "oklch(0.708 0 0)",
    "--popover": "oklch(0.205 0 0)",
    "--popover-foreground": "oklch(0.985 0 0)",
    "--primary": "oklch(0.448 0.119 151.328)",
    "--primary-foreground": "oklch(0.982 0.018 155.826)",
    "--radius": "0.625rem",
    "--ring": "oklch(0.556 0 0)",
    "--secondary": "oklch(0.274 0.006 286.033)",
    "--secondary-foreground": "oklch(0.985 0 0)",
    "--sidebar": "oklch(0.205 0 0)",
    "--sidebar-accent": "oklch(0.269 0 0)",
    "--sidebar-accent-foreground": "oklch(0.985 0 0)",
    "--sidebar-border": "oklch(1 0 0 / 10%)",
    "--sidebar-foreground": "oklch(0.985 0 0)",
    "--sidebar-primary": "oklch(0.723 0.219 149.579)",
    "--sidebar-primary-foreground": "oklch(0.982 0.018 155.826)",
    "--sidebar-ring": "oklch(0.556 0 0)"
  },
} as const

export type ThemeCssVars = typeof themeCssVars
export type ThemeId = keyof typeof themeCssVars
